const express = require('express');
const multer = require('multer');
const db = require('./db');
const privacyAccess = require('./privacy-access');
const mediaStorage = require('./media-storage');

const router = express.Router();
const SOURCE_TYPES = new Set(['birth_certificate','death_certificate','marriage_record','census','school_record','church_record','land_record','newspaper','photograph','interview','online_archive','other']);
const CONFIDENCE = new Set(['confirmed','probable','uncertain','disputed']);
const SUBJECTS = new Set(['person','relationship','event','story']);
const evidenceUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 20 * 1024 * 1024 }, fileFilter: (req, file, cb) => cb(null, ['application/pdf','image/jpeg','image/png','image/webp','image/gif','image/tiff','text/plain'].includes(file.mimetype)) });

async function initializeEvidence() {
  await Promise.all([db.ready, privacyAccess.ready, mediaStorage.ready]);
  await db.query("CREATE TABLE IF NOT EXISTS research_sources (id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE, source_type VARCHAR(40) NOT NULL DEFAULT 'other', title VARCHAR(300) NOT NULL, author VARCHAR(300), repository VARCHAR(300), repository_url TEXT, archive_location TEXT, call_number VARCHAR(200), publication_info TEXT, source_date VARCHAR(100), description TEXT, citation_template TEXT, created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP)");
  await db.query("CREATE TABLE IF NOT EXISTS source_citations (id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE, source_id INTEGER NOT NULL REFERENCES research_sources(id) ON DELETE CASCADE, subject_type VARCHAR(20) NOT NULL, subject_id INTEGER NOT NULL, fact_key VARCHAR(100), claim_value TEXT, page VARCHAR(200), record_identifier VARCHAR(200), citation_text TEXT, transcription TEXT, translation TEXT, confidence VARCHAR(20) NOT NULL DEFAULT 'probable', research_note TEXT, conflict_group VARCHAR(120), created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP)");
  await db.query("CREATE TABLE IF NOT EXISTS evidence_media (citation_id INTEGER NOT NULL REFERENCES source_citations(id) ON DELETE CASCADE, media_id UUID NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE, caption VARCHAR(300), created_at TIMESTAMP NOT NULL DEFAULT now(), PRIMARY KEY (citation_id, media_id))");
  await db.query('CREATE INDEX IF NOT EXISTS idx_sources_family ON research_sources(family_id, title)');
  await db.query('CREATE INDEX IF NOT EXISTS idx_citations_subject ON source_citations(family_id, subject_type, subject_id)');
}
const ready = initializeEvidence();
function err(status, message) { return Object.assign(new Error(message), { status }); }
function text(value, max, label) { const v = String(value ?? '').trim(); if (v.length > max) throw err(400, `${label} must be under ${max} characters`); return v || null; }
function level(role) { return privacyAccess.ROLE_LEVEL[role] || 0; }
function canManage(row, req) { return Number(row.created_by_user_id) === Number(req.session.userId) || level(req.family.role) >= privacyAccess.ROLE_LEVEL.admin; }
async function subjectVisible(req, type, id) {
  if (type === 'person') { const r=await db.query('SELECT * FROM persons WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[id,req.family.id]); if(!r.rows[0])return false; const v=privacyAccess.serializePerson(r.rows[0],req.session.userId,req.family.role); return Boolean(v&&!v.privacy_redacted); }
  if (type === 'event') return Boolean((await db.query('SELECT id FROM life_events WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[id,req.family.id])).rows[0]);
  if (type === 'relationship') return Boolean((await db.query('SELECT r.id FROM relationships r JOIN persons p ON p.id=r.person1_id WHERE r.id=$1 AND p.family_id=$2 AND p.deleted_at IS NULL',[id,req.family.id])).rows[0]);
  if (type === 'story') return Boolean((await db.query('SELECT id FROM family_stories WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[id,req.family.id])).rows[0]);
  return false;
}
async function subjectVisibleForCitation(citationId, req) {
  const r = await db.query('SELECT subject_type, subject_id, family_id FROM source_citations WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL', [citationId, req.family.id]);
  return Boolean(r.rows[0] && await subjectVisible(req, r.rows[0].subject_type, r.rows[0].subject_id));
}
function source(row) { return { ...row, citation_count: Number(row.citation_count || 0) }; }
function registerRoutes(app, middleware) {
  const {requireAuth,requireApproved,requireFamily,requireRole}=middleware;
  app.use('/api/evidence',requireAuth,requireApproved,requireFamily,router);
  router.get('/sources',async(req,res,next)=>{try{await ready;const q=String(req.query.q||'').trim();const r=await db.query("SELECT s.*,count(c.id)::int citation_count FROM research_sources s LEFT JOIN source_citations c ON c.source_id=s.id AND c.deleted_at IS NULL WHERE s.family_id=$1 AND s.deleted_at IS NULL AND ($2='' OR s.title ILIKE '%'||$2||'%' OR s.repository ILIKE '%'||$2||'%') GROUP BY s.id ORDER BY s.updated_at DESC,s.id DESC",[req.family.id,q]);res.json({sources:r.rows.map(source)});}catch(e){next(e);}});
  router.post('/sources',requireRole('contributor'),async(req,res,next)=>{try{await ready;const b=req.body||{},type=String(b.source_type||'other');if(!SOURCE_TYPES.has(type))throw err(400,'Invalid source type');const title=text(b.title,300,'Title');if(!title)throw err(400,'Title is required');const r=await db.query('INSERT INTO research_sources (family_id,source_type,title,author,repository,repository_url,archive_location,call_number,publication_info,source_date,description,citation_template,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[req.family.id,type,title,text(b.author,300,'Author'),text(b.repository,300,'Repository'),text(b.repository_url,2000,'Repository URL'),text(b.archive_location,1000,'Archive location'),text(b.call_number,200,'Call number'),text(b.publication_info,2000,'Publication info'),text(b.source_date,100,'Source date'),text(b.description,5000,'Description'),text(b.citation_template,2000,'Citation template'),req.session.userId]);res.status(201).json({source:source(r.rows[0])});}catch(e){next(e);}});
  router.get('/citations',async(req,res,next)=>{try{await ready;const type=String(req.query.subject_type||''),id=Number(req.query.subject_id);if(!SUBJECTS.has(type)||!Number.isInteger(id)||!(await subjectVisible(req,type,id)))return res.status(404).json({error:'Subject not found'});const r=await db.query("SELECT c.*,s.title source_title,s.source_type,s.repository,COALESCE(json_agg(json_build_object('id',m.id,'url','/api/media/'||m.id,'caption',em.caption,'mime_type',m.mime_type,'name',m.original_name)) FILTER(WHERE m.id IS NOT NULL),'[]') media FROM source_citations c JOIN research_sources s ON s.id=c.source_id LEFT JOIN evidence_media em ON em.citation_id=c.id LEFT JOIN media_assets m ON m.id=em.media_id WHERE c.family_id=$1 AND c.subject_type=$2 AND c.subject_id=$3 AND c.deleted_at IS NULL AND s.deleted_at IS NULL GROUP BY c.id,s.title,s.source_type,s.repository ORDER BY c.created_at DESC",[req.family.id,type,id]);res.json({citations:r.rows});}catch(e){next(e);}});
  router.post('/citations',requireRole('contributor'),async(req,res,next)=>{try{await ready;const b=req.body||{},type=String(b.subject_type||''),subjectId=Number(b.subject_id);if(!SUBJECTS.has(type)||!Number.isInteger(subjectId)||!(await subjectVisible(req,type,subjectId)))throw err(404,'Subject not found');if(!(await db.query('SELECT id FROM research_sources WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[b.source_id,req.family.id])).rows[0])throw err(404,'Source not found');const confidence=String(b.confidence||'probable');if(!CONFIDENCE.has(confidence))throw err(400,'Invalid confidence');const r=await db.query('INSERT INTO source_citations (family_id,source_id,subject_type,subject_id,fact_key,claim_value,page,record_identifier,citation_text,transcription,translation,confidence,research_note,conflict_group,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *',[req.family.id,b.source_id,type,subjectId,text(b.fact_key,100,'Fact key'),text(b.claim_value,10000,'Claim'),text(b.page,200,'Page'),text(b.record_identifier,200,'Record identifier'),text(b.citation_text,5000,'Citation'),text(b.transcription,20000,'Transcription'),text(b.translation,20000,'Translation'),confidence,text(b.research_note,10000,'Research note'),text(b.conflict_group,120,'Conflict group'),req.session.userId]);res.status(201).json({citation:r.rows[0]});}catch(e){next(e);}});
  router.post('/citations/:id/media',requireRole('contributor'),evidenceUpload.single('file'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'No evidence file uploaded'});const c=(await db.query('SELECT id FROM source_citations WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[req.params.id,req.family.id])).rows[0];if(!c)return res.status(404).json({error:'Citation not found'});const asset=await mediaStorage.save(req,req.file,{purpose:'evidence',originalName:req.file.originalname});await db.query('INSERT INTO evidence_media(citation_id,media_id,caption) VALUES($1,$2,$3)',[c.id,asset.id,text(req.body.caption,300,'Caption')]);res.status(201).json({media:asset});}catch(e){next(e);}});
  router.delete('/citations/:id',requireRole('contributor'),async(req,res,next)=>{try{const r=await db.query('UPDATE source_citations SET deleted_at=now(),updated_at=now() WHERE id=$1 AND family_id=$2 AND (created_by_user_id=$3 OR $4>=3) RETURNING id',[req.params.id,req.family.id,req.session.userId,level(req.family.role)]);if(!r.rows[0])return res.status(404).json({error:'Citation not found'});res.json({success:true});}catch(e){next(e);}});
}
module.exports={ready,registerRoutes,subjectVisible,subjectVisibleForCitation};
