const express = require('express');
const multer = require('multer');
const crypto = require('crypto');
const QRCode = require('qrcode');
const db = require('./db');
const familyAccess = require('./family-access');
const privacyAccess = require('./privacy-access');
const mediaStorage = require('./media-storage');
const archiveAccess = require('./archive-access');

const router = express.Router();
const VISIBILITIES = new Set(['family','contributors','admins','private']);
const MEMORY_TYPES = new Set(['photo','video','audio','document','story','recipe','memorial']);
const memoryUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 100 * 1024 * 1024 }, fileFilter: (req, file, cb) => cb(null, ['image/jpeg','image/png','image/webp','image/gif','image/tiff','application/pdf','text/plain','audio/mpeg','audio/wav','audio/ogg','audio/mp4','video/mp4','video/webm','video/quicktime'].includes(file.mimetype)) });

async function initializeMemories() {
  await Promise.all([db.ready, familyAccess.ready, privacyAccess.ready, mediaStorage.ready, archiveAccess.ready]);
  await db.query(`CREATE TABLE IF NOT EXISTS memory_albums (
    id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    title VARCHAR(220) NOT NULL, description TEXT, cover_media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL,
    visibility VARCHAR(20) NOT NULL DEFAULT 'family', created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
  )`);
  await db.query(`CREATE TABLE IF NOT EXISTS memory_items (
    id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE,
    album_id INTEGER REFERENCES memory_albums(id) ON DELETE SET NULL, media_id UUID REFERENCES media_assets(id) ON DELETE SET NULL,
    story_id INTEGER REFERENCES family_stories(id) ON DELETE SET NULL, memory_type VARCHAR(20) NOT NULL DEFAULT 'photo',
    title VARCHAR(220) NOT NULL, caption TEXT, taken_date VARCHAR(80), place VARCHAR(255), photographer VARCHAR(255),
    transcript TEXT, translation TEXT, visibility VARCHAR(20) NOT NULL DEFAULT 'family', public_token UUID UNIQUE,
    memorial_person_id INTEGER REFERENCES persons(id) ON DELETE SET NULL, created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
  )`);
  await db.query(`CREATE TABLE IF NOT EXISTS memory_people (memory_id INTEGER NOT NULL REFERENCES memory_items(id) ON DELETE CASCADE, person_id INTEGER NOT NULL REFERENCES persons(id) ON DELETE CASCADE, PRIMARY KEY(memory_id,person_id))`);
  await db.query(`CREATE TABLE IF NOT EXISTS family_recipes (
    id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE, title VARCHAR(220) NOT NULL,
    story TEXT, ingredients TEXT, instructions TEXT, origin VARCHAR(255), contributor VARCHAR(255), visibility VARCHAR(20) NOT NULL DEFAULT 'family',
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
  )`);
  await db.query(`CREATE TABLE IF NOT EXISTS family_memorials (
    id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE, person_id INTEGER REFERENCES persons(id) ON DELETE SET NULL,
    title VARCHAR(220) NOT NULL, message TEXT, service_date VARCHAR(80), service_place VARCHAR(255), visibility VARCHAR(20) NOT NULL DEFAULT 'family',
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now(), deleted_at TIMESTAMP
  )`);
  await db.query(`CREATE TABLE IF NOT EXISTS family_reminders (
    id SERIAL PRIMARY KEY, family_id INTEGER NOT NULL REFERENCES families(id) ON DELETE CASCADE, person_id INTEGER REFERENCES persons(id) ON DELETE CASCADE,
    title VARCHAR(220) NOT NULL, reminder_type VARCHAR(30) NOT NULL DEFAULT 'on_this_day', month SMALLINT, day SMALLINT, event_date VARCHAR(80), notes TEXT,
    created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMP NOT NULL DEFAULT now(), updated_at TIMESTAMP NOT NULL DEFAULT now()
  )`);
  await db.query('CREATE INDEX IF NOT EXISTS idx_memory_items_family ON memory_items(family_id,created_at DESC) WHERE deleted_at IS NULL');
  await db.query('CREATE INDEX IF NOT EXISTS idx_memory_people_person ON memory_people(person_id)');
}
const ready = initializeMemories();
function error(status,message){return Object.assign(new Error(message),{status});}
function text(v,max,label){const s=String(v??'').trim();if(s.length>max)throw error(400,`${label} must be under ${max} characters`);return s||null;}
function roleLevel(role){return privacyAccess.ROLE_LEVEL[role]||0;}
function visible(row,req){if(Number(row.created_by_user_id)===Number(req.session.userId))return true;const l=roleLevel(req.family.role);return row.visibility==='family'?l>=privacyAccess.ROLE_LEVEL.viewer:row.visibility==='contributors'?l>=privacyAccess.ROLE_LEVEL.contributor:row.visibility==='admins'?l>=privacyAccess.ROLE_LEVEL.admin:false;}
async function peopleFor(itemIds){if(!itemIds.length)return new Map();const r=await db.query('SELECT mp.memory_id,p.id,p.first_name,p.last_name FROM memory_people mp JOIN persons p ON p.id=mp.person_id WHERE mp.memory_id=ANY($1) AND p.deleted_at IS NULL ORDER BY p.last_name,p.first_name',[itemIds]);const map=new Map(itemIds.map(id=>[Number(id),[]]));r.rows.forEach(row=>map.get(Number(row.memory_id))?.push({id:row.id,name:`${row.first_name} ${row.last_name}`.trim()}));return map;}
function serialize(row,tagMap){return {...row,media_url:row.media_id?`/api/media/${row.media_id}`:null,people:tagMap.get(Number(row.id))||[]};}
async function listItems(req,res,next){try{await ready;const params=[req.family.id],where=['m.family_id=$1','m.deleted_at IS NULL'];if(req.query.type){params.push(String(req.query.type));where.push(`m.memory_type=$${params.length}`);}if(req.query.album_id){params.push(Number(req.query.album_id));where.push(`m.album_id=$${params.length}`);}if(req.query.person_id){params.push(Number(req.query.person_id));where.push(`EXISTS(SELECT 1 FROM memory_people mp WHERE mp.memory_id=m.id AND mp.person_id=$${params.length})`);}const r=await db.query(`SELECT m.*,a.original_name,a.mime_type,a.size_bytes FROM memory_items m LEFT JOIN media_assets a ON a.id=m.media_id WHERE ${where.join(' AND ')} ORDER BY COALESCE(m.taken_date,'9999'),m.created_at DESC`,params);const tags=await peopleFor(r.rows.map(x=>x.id));res.json({items:r.rows.filter(x=>visible(x,req)).map(x=>serialize(x,tags))});}catch(e){next(e);}}
async function listAlbums(req,res,next){try{await ready;const r=await db.query('SELECT a.*,count(m.id)::int item_count FROM memory_albums a LEFT JOIN memory_items m ON m.album_id=a.id AND m.deleted_at IS NULL WHERE a.family_id=$1 AND a.deleted_at IS NULL GROUP BY a.id ORDER BY a.updated_at DESC',[req.family.id]);res.json({albums:r.rows.filter(x=>visible(x,req))});}catch(e){next(e);}}
async function createItem(req,res,next){try{await ready;const b=req.body||{},type=String(b.memory_type||'photo');if(!MEMORY_TYPES.has(type))throw error(400,'Invalid memory type');const title=text(b.title,220,'Title')||req.file?.originalname||'Untitled memory';const visibility=String(b.visibility||'family');if(!VISIBILITIES.has(visibility))throw error(400,'Invalid visibility');let mediaId=null;if(req.file){const asset=await mediaStorage.save(req,req.file,{purpose:'memory',originalName:req.file.originalname});mediaId=asset.id;}const publicToken=String(b.public_token||'')==='true'?crypto.randomUUID():null;const r=await db.query('INSERT INTO memory_items(family_id,album_id,media_id,story_id,memory_type,title,caption,taken_date,place,photographer,transcript,translation,visibility,public_token,memorial_person_id,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *',[req.family.id,b.album_id||null,mediaId,b.story_id||null,type,title,text(b.caption,10000,'Caption'),text(b.taken_date,80,'Date'),text(b.place,255,'Place'),text(b.photographer,255,'Photographer'),text(b.transcript,100000,'Transcript'),text(b.translation,100000,'Translation'),visibility,publicToken,b.memorial_person_id||null,req.session.userId]);const ids=JSON.parse(b.person_ids||'[]');for(const id of Array.isArray(ids)?ids:[])await db.query('INSERT INTO memory_people(memory_id,person_id) SELECT $1,id FROM persons WHERE id=$2 AND family_id=$3 AND deleted_at IS NULL ON CONFLICT DO NOTHING',[r.rows[0].id,id,req.family.id]);res.status(201).json({item:serialize(r.rows[0],new Map())});}catch(e){next(e);}}
function registerRoutes(app,middleware){const {requireAuth,requireApproved,requireFamily,requireRole}=middleware;app.use('/api/memories',requireAuth,requireApproved,requireFamily,router);
  router.get('/overview',async(req,res,next)=>{try{await ready;const [i,a,r,m]=await Promise.all([db.query('SELECT count(*)::int count FROM memory_items WHERE family_id=$1 AND deleted_at IS NULL',[req.family.id]),db.query('SELECT count(*)::int count FROM memory_albums WHERE family_id=$1 AND deleted_at IS NULL',[req.family.id]),db.query('SELECT count(*)::int count FROM family_recipes WHERE family_id=$1 AND deleted_at IS NULL',[req.family.id]),db.query('SELECT count(*)::int count FROM family_memorials WHERE family_id=$1 AND deleted_at IS NULL',[req.family.id])]);res.json({stats:{memories:i.rows[0].count,albums:a.rows[0].count,recipes:r.rows[0].count,memorials:m.rows[0].count}});}catch(e){next(e);}});
  router.get('/items',listItems);router.post('/items',requireRole('contributor'),memoryUpload.single('file'),createItem);
  router.patch('/items/:id',requireRole('contributor'),async(req,res,next)=>{try{const old=(await db.query('SELECT * FROM memory_items WHERE id=$1 AND family_id=$2 AND deleted_at IS NULL',[req.params.id,req.family.id])).rows[0];if(!old||!visible(old,req))return res.status(404).json({error:'Memory not found'});const b=req.body||{};const r=await db.query('UPDATE memory_items SET title=COALESCE($1,title),caption=COALESCE($2,caption),taken_date=COALESCE($3,taken_date),place=COALESCE($4,place),photographer=COALESCE($5,photographer),transcript=COALESCE($6,transcript),translation=COALESCE($7,translation),visibility=COALESCE($8,visibility),updated_at=now() WHERE id=$9 RETURNING *',[text(b.title,220,'Title'),text(b.caption,10000,'Caption'),text(b.taken_date,80,'Date'),text(b.place,255,'Place'),text(b.photographer,255,'Photographer'),text(b.transcript,100000,'Transcript'),text(b.translation,100000,'Translation'),b.visibility,req.params.id]);res.json({item:serialize(r.rows[0],new Map())});}catch(e){next(e);}});
  router.delete('/items/:id',requireRole('contributor'),async(req,res,next)=>{try{const r=await db.query('UPDATE memory_items SET deleted_at=now(),updated_at=now() WHERE id=$1 AND family_id=$2 AND (created_by_user_id=$3 OR $4>=3) RETURNING id',[req.params.id,req.family.id,req.session.userId,roleLevel(req.family.role)]);if(!r.rows[0])return res.status(404).json({error:'Memory not found'});res.json({success:true});}catch(e){next(e);}});
  router.get('/albums',listAlbums);router.post('/albums',requireRole('contributor'),async(req,res,next)=>{try{const b=req.body||{},title=text(b.title,220,'Title');if(!title)throw error(400,'Title is required');const r=await db.query('INSERT INTO memory_albums(family_id,title,description,visibility,created_by_user_id) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.family.id,title,text(b.description,5000,'Description'),b.visibility||'family',req.session.userId]);res.status(201).json({album:r.rows[0]});}catch(e){next(e);}});
  router.get('/recipes',async(req,res,next)=>{try{const r=await db.query('SELECT * FROM family_recipes WHERE family_id=$1 AND deleted_at IS NULL ORDER BY updated_at DESC',[req.family.id]);res.json({recipes:r.rows.filter(x=>visible(x,req))});}catch(e){next(e);}});router.post('/recipes',requireRole('contributor'),async(req,res,next)=>{try{const b=req.body||{},title=text(b.title,220,'Title');if(!title)throw error(400,'Title is required');const r=await db.query('INSERT INTO family_recipes(family_id,title,story,ingredients,instructions,origin,contributor,visibility,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.family.id,title,text(b.story,10000,'Story'),text(b.ingredients,10000,'Ingredients'),text(b.instructions,20000,'Instructions'),text(b.origin,255,'Origin'),text(b.contributor,255,'Contributor'),b.visibility||'family',req.session.userId]);res.status(201).json({recipe:r.rows[0]});}catch(e){next(e);}});
  router.get('/memorials',async(req,res,next)=>{try{const r=await db.query('SELECT m.*,p.first_name,p.last_name FROM family_memorials m LEFT JOIN persons p ON p.id=m.person_id WHERE m.family_id=$1 AND m.deleted_at IS NULL ORDER BY m.service_date DESC NULLS LAST',[req.family.id]);res.json({memorials:r.rows.filter(x=>visible(x,req))});}catch(e){next(e);}});router.post('/memorials',requireRole('contributor'),async(req,res,next)=>{try{const b=req.body||{},title=text(b.title,220,'Title');if(!title)throw error(400,'Title is required');const r=await db.query('INSERT INTO family_memorials(family_id,person_id,title,message,service_date,service_place,visibility,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.family.id,b.person_id||null,title,text(b.message,20000,'Message'),text(b.service_date,80,'Service date'),text(b.service_place,255,'Service place'),b.visibility||'family',req.session.userId]);res.status(201).json({memorial:r.rows[0]});}catch(e){next(e);}});
  router.get('/calendar',async(req,res,next)=>{try{const r=await db.query(`SELECT id,first_name,last_name,'birthday' reminder_type,birth_date event_date FROM persons WHERE family_id=$1 AND deleted_at IS NULL AND birth_date IS NOT NULL UNION ALL SELECT id,first_name,last_name,'memorial' reminder_type,death_date event_date FROM persons WHERE family_id=$1 AND deleted_at IS NULL AND death_date IS NOT NULL ORDER BY event_date`,[req.family.id,req.family.id]);res.json({calendar:r.rows});}catch(e){next(e);}});
  router.post('/items/:id/qr',requireRole('contributor'),async(req,res,next)=>{try{const r=await db.query('UPDATE memory_items SET public_token=COALESCE(public_token,$1),updated_at=now() WHERE id=$2 AND family_id=$3 RETURNING public_token',[crypto.randomUUID(),req.params.id,req.family.id]);if(!r.rows[0])return res.status(404).json({error:'Memory not found'});const url=`${process.env.PUBLIC_APP_URL||'http://localhost:4000'}/memory/${r.rows[0].public_token}`,png=await QRCode.toBuffer(url,{width:800,margin:2,color:{dark:'#33261c',light:'#fffdf8'}});res.type('png').set('Content-Disposition',`attachment; filename="memory-${req.params.id}-qr.png"`).send(png);}catch(e){next(e);}});
}
async function publicMemory(req,res,next){try{await ready;const r=await db.query('SELECT m.*,a.object_name,a.mime_type,a.original_name FROM memory_items m LEFT JOIN media_assets a ON a.id=m.media_id WHERE m.public_token=$1 AND m.deleted_at IS NULL',[req.params.token]);if(!r.rows[0])return res.status(404).json({error:'Memory not found'});const row=r.rows[0];res.json({memory:{id:row.id,title:row.title,caption:row.caption,taken_date:row.taken_date,place:row.place,photographer:row.photographer,transcript:row.transcript,media_type:row.memory_type,media_url:row.media_id?`/api/public/memories/${req.params.token}/media`:null}});}catch(e){next(e);}}
async function publicMemoryMedia(req,res,next){try{await ready;const r=await db.query('SELECT a.* FROM memory_items m JOIN media_assets a ON a.id=m.media_id WHERE m.public_token=$1 AND m.deleted_at IS NULL',[req.params.token]);if(!r.rows[0])return res.status(404).end();const buffer=await mediaStorage.readAsset(r.rows[0]);res.type(r.rows[0].mime_type).set('Cache-Control','public,max-age=3600').send(buffer);}catch(e){next(e);}}
function publicMemoryPage(req,res){const token=encodeURIComponent(req.params.token);res.type('html').send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Family memory</title><style>body{margin:0;background:#f5eddd;color:#33261c;font:16px system-ui,sans-serif}.page{max-width:820px;margin:0 auto;padding:8vh 20px}.card{background:#fffdf8;border:1px solid #dfd4c0;border-radius:24px;overflow:hidden;box-shadow:0 20px 60px #33261c1c}.media{background:#e6ddcd;min-height:260px;display:grid;place-items:center}.media img,.media video{max-width:100%;max-height:65vh}.copy{padding:30px}.kicker{color:#987238;font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}h1{font:700 clamp(2rem,6vw,4rem) Georgia;margin:8px 0 16px}p{line-height:1.7;color:#716453}.credit{font-size:13px;color:#8d7b64}</style></head><body><main class="page"><article class="card"><div class="media" id="media"></div><div class="copy" id="copy"><p class="kicker">A family memory</p><p>Loading...</p></div></article></main><script>fetch('/api/public/memories/${token}').then(r=>r.ok?r.json():Promise.reject()).then(({memory:m})=>{document.title=m.title;document.getElementById('media').innerHTML=m.media_url?(m.media_type==='video'?'<video controls src="'+m.media_url+'"></video>':'<img src="'+m.media_url+'" alt="">'):'<span>✦</span>';document.getElementById('copy').innerHTML='<p class="kicker">A family memory · '+(m.taken_date||'')+'</p><h1>'+safe(m.title)+'</h1><p>'+safe(m.caption||'')+'</p><p class="credit">'+safe([m.place,m.photographer].filter(Boolean).join(' · '))+'</p>'+(m.transcript?'<p>'+safe(m.transcript)+'</p>':'');}).catch(()=>document.getElementById('copy').innerHTML='<h1>Memory unavailable</h1><p>This private link may have expired or been removed.</p>');function safe(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</script></body></html>`);}
module.exports={ready,registerRoutes,publicMemory,publicMemoryMedia,publicMemoryPage};
