const express = require('express');
const db = require('./db');
const platform = require('./platform-access');
const router = express.Router();
const configured = Boolean(process.env.DARAJA_CONSUMER_KEY && process.env.DARAJA_CONSUMER_SECRET && process.env.DARAJA_SHORTCODE && process.env.DARAJA_PASSKEY && process.env.DARAJA_CALLBACK_URL);
const env = String(process.env.DARAJA_ENV || 'sandbox').toLowerCase() === 'production' ? 'production' : 'sandbox';
const base = env === 'production' ? 'https://api.safaricom.co.ke' : 'https://sandbox.safaricom.co.ke';
const fail=(status,message)=>Object.assign(new Error(message),{status});
const normalizePhone=v=>{const d=String(v||'').replace(/\D/g,'');return d.startsWith('0')&&d.length===10?'254'+d.slice(1):d};
async function initialize(){await Promise.all([db.ready,platform.ready]);await db.query('CREATE TABLE IF NOT EXISTS payment_transactions(id BIGSERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,provider VARCHAR(30) NOT NULL,checkout_request_id VARCHAR(120) UNIQUE,merchant_request_id VARCHAR(120),amount_kes INTEGER NOT NULL,phone VARCHAR(30),mpesa_receipt VARCHAR(60) UNIQUE,status VARCHAR(30) NOT NULL DEFAULT \'initiated\',result_code VARCHAR(30),result_description TEXT,raw_callback JSONB,created_at TIMESTAMP DEFAULT now(),updated_at TIMESTAMP DEFAULT now())');await db.query('CREATE TABLE IF NOT EXISTS payment_status_history(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT REFERENCES payment_transactions(id) ON DELETE CASCADE,status VARCHAR(30) NOT NULL,note TEXT,created_at TIMESTAMP DEFAULT now())');await db.query('CREATE TABLE IF NOT EXISTS payment_receipts(id BIGSERIAL PRIMARY KEY,transaction_id BIGINT REFERENCES payment_transactions(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id),receipt_number VARCHAR(80) UNIQUE NOT NULL,amount_kes INTEGER NOT NULL,issued_at TIMESTAMP DEFAULT now())');await db.query('CREATE TABLE IF NOT EXISTS payment_gifts(id BIGSERIAL PRIMARY KEY,sponsor_user_id INTEGER REFERENCES users(id),recipient_email VARCHAR(255),amount_kes INTEGER NOT NULL,status VARCHAR(30) DEFAULT \'pending\',created_at TIMESTAMP DEFAULT now())');await db.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS access_type VARCHAR(30) NOT NULL DEFAULT \'lifetime\'');await db.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS access_expires_at TIMESTAMP');}
const ready=initialize();
function registerRoutes(app){const {requireSession}=platform;app.use('/api/payments',requireSession,router);router.get('/config',(req,res)=>res.json({manual:{enabled:true,amount_kes:platform.PAYMENT_AMOUNT_KES,phone:platform.PAYMENT_PHONE},daraja:{enabled:configured,environment:env}}));router.get('/history',async(req,res,next)=>{try{res.json({transactions:(await db.query('SELECT * FROM payment_transactions WHERE user_id=$1 ORDER BY created_at DESC',[req.session.userId])).rows});}catch(e){next(e);}});router.post('/stk-push',async(req,res,next)=>{try{if(!configured)return res.status(503).json({error:'Daraja is not configured. Manual Send Money remains available.',code:'DARAJA_NOT_CONFIGURED'});res.status(501).json({error:'Daraja client credentials are configured but STK Push activation is pending'});}catch(e){next(e);}});}
module.exports={ready,configured,registerRoutes};
